[agent]

persistent_facts = [
  "Todo fluxo de desenvolvimento, ao ser iniciado, deve-se fazer um git pull na main e criar uma nova branch baseada nela. O nome dessa branch deve ser sugestiva a especificação informada ou ao prefixo da história que está sendo desenvolvida. Nunca implementar nada diretamente na main, a não ser que seja expressamente solicitado.",
  "Todo code review deve ser propositivo e registrar todos os apontamentos na especificação da história que está sendo analisada. As alterações podem ser sugeridas, mas só aplique se for expressamente solicitado. Quando essas alterações forem aplicadas, seja via fluxo de code review ou de desenvolvimento (analisando os apontamentos da especificação original), deve-se atualizar o documento marcando cada item concluído."
]
