# Kustomization overlay homologacao - keycloak-auth - cluster-kubernetes
# Ambiente: homologacao — customizações de validação pré-produção
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
