# Kustomization overlay production - keycloak-auth - cluster-kubernetes
# Ambiente: production — customizações de alta disponibilidade e segurança
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
